# Generated by Django 5.2.3 on 2025-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('like', models.IntegerField()),
                ('caption', models.TextField()),
                ('password', models.CharField()),
            ],
        ),
    ]
