# Generated by Django 5.2.3 on 2025-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('posts', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
